#cloud-config
# You will need to edit this file before creating your new servers
users:
  - name: example
    primary_group: example
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPcIFTulPt0iCVf29Cn3HJ1D38GsDtxbBYcakSBw3BUy jparras1@my.bcit.ca

packages:
  - ripgrep
  - rsync

runcmd:
  - sed -i 's/^#\(Storage=auto\)/\1/' /etc/systemd/journald.conf
  - sed -i -e '/^PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
  - systemctl restart ssh
  - systemctl restart systemd-journald
  - sudo apt update
  - sudo apt upgrade
  - sudo apt install nginx
  - sudo apt install ufw
  - sudo ufw default deny incoming
  - sudo ufw default allow outgoing
  - sudo ufw allow ssh
  - sudo ufw allow http
  - sudo ufw enable

